default: &default
  adapter:  postgresql
  host:     localhost
  #port:     5432
  encoding: unicode
  username:
  password:
  pool:     5

development:
  <<: *default
  database: blog_development

test: &test
  <<: *default
  database: blog_test

cucumber:
  <<: *test
